import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: "6942919b-77eb-44fb-bf0b-af0942e32c11",
    firstName: "Gautam",
    lastName: "Bm",
    username: "gautam.bm",
    password: "gautam123",
    picUrl: "https://github.com/gautam-balamurali.png",
    bgUrl: "https://picsum.photos/224/320?random=1",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    bio: "Owns Sochenge",
    websiteUrl: "https://gautam-balamurali.netlify.app",
    websiteName: "gautam-bm.com",
  },
  {
    _id: "afadbcf4-ea27-4e30-a058-acaf101a9f7c",
    firstName: "Adarsh",
    lastName: "Balika",
    username: "adarshbalika",
    password: "adarshBalika123",
    picUrl: "http://bit.ly/42Zm7tM",
    bgUrl: "https://picsum.photos/224/320?random=1",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    bio: "This is my bio.",
    websiteUrl: "https://www.google.com",
    websiteName: "gautam-bm.com",
  },
  {
    _id: "bc5cfc5b-62dc-43e3-aac1-d920066e7427",
    firstName: "Elon",
    lastName: "Mast",
    username: "elonmast",
    password: "elonMast123",
    picUrl: "http://bit.ly/42Zm7tM",
    bgUrl: "https://picsum.photos/224/320?random=2",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    bio: "This is my bio.",
    websiteUrl: "https://www.google.com",
    websiteName: "gautam-bm.com",
  },
  {
    _id: "55a7e27f-1ed9-434b-87e4-2e0b308c4b16",
    firstName: "Sad",
    lastName: "Moustachim",
    username: "moustachim69",
    password: "sadMoustachim123",
    picUrl:
      "https://res.cloudinary.com/dbe8yf165/image/upload/v1688578533/twitlyx/mushu_lswrux.jpg",
    bgUrl: "https://picsum.photos/224/320?random=3",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    bio: "This is my bio.",
    websiteUrl: "https://www.google.com",
    websiteName: "gautam-bm.com",
  },
  {
    _id: "9d2f44ab-96fc-4744-b83d-e7cbc3be21b5",
    firstName: "Yess",
    lastName: "Patidar",
    username: "wanderlust420",
    password: "yesPatidar123",
    picUrl:
      "https://res.cloudinary.com/dbe8yf165/image/upload/v1688578534/twitlyx/yespatidar_jp345o.jpg",
    bgUrl: "https://picsum.photos/224/320?random=4",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    bio: "This is my bio.",
    websiteUrl: "https://www.google.com",
    websiteName: "gautam-bm.com",
  },
  {
    _id: "e29082cc-d57b-4f3d-a863-0e2dc4ed02ba",
    firstName: "Shubhi",
    lastName: "K",
    username: "sasta_arjit",
    password: "shubumK123",
    picUrl: "http://bit.ly/42Zm7tM",
    bgUrl: "https://picsum.photos/224/320?random=5",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    bio: "This is my bio.",
    websiteUrl: "https://www.google.com",
    websiteName: "gautam-bm.com",
  },
  {
    _id: "09ab1282-7e8b-4658-b2be-326504d10f68",
    firstName: "Princess",
    lastName: "Rani",
    username: "silentQueen",
    password: "princess123",
    picUrl: "http://bit.ly/42Zm7tM",
    bgUrl: "https://picsum.photos/224/320?random=6",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    bio: "This is my bio.",
    websiteUrl: "https://www.google.com",
    websiteName: "gautam-bm.com",
  },
];
